version: '3'
services:
  whatsminer2mqtt:
    container_name: whatsminer2mqtt
    image: tediore/whatsminer2mqtt:latest
    environment:
    - MQTT_HOST=10.0.0.2
    - MQTT_PORT=1883
    - MQTT_USER=user
    - MQTT_PASSWORD=password
    - BASE_TOPIC=whatsminer2mqtt
    - HOME_ASSISTANT=True
    - MINER_IP=10.0.1.4
    - INTERVAL=10
    - LOG_LEVEL=debug
    restart: unless-stopped